version: "3"

services:
  reverse-proxy:
    image: traefik:v2.5.3
    restart: unless-stopped
    # command: --providers.docker
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./certs:/certs 
  # origin:
  #   image: python
  #   entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"

  #   labels:
  #     # Enable this container to be mapped by traefik
  #     - "traefik.enable=true"
  #     # URL to reach this container
  #     - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
  #     # If port is different than 80, use the following service:
  #     - "traefik.http.services.origin.loadbalancer.server.port=80"
  #     # Activation of TLS
  #     - "traefik.http.routers.origin.tls=true"
  origin:
    image: python:3.6.9-alpine
    volumes:
      - /home/lzy/pcap/traefik:/pcap
      - /home/lzy/logs/traefik:/logs
      - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
      - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
      - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
      # - /home/lzy/my_repo/http2smuggler/echo_server/sleep.py:/sleep.py
    command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
    labels:
      # Enable this container to be mapped by traefik
      - "traefik.enable=true"
      # URL to reach this container
      - "traefik.http.routers.origin.rule=Host(`origin.docker.localhost`)"
      # If port is different than 80, use the following service:
      - "traefik.http.services.origin.loadbalancer.server.port=80"
      # Activation of TLS
      - "traefik.http.routers.origin.tls=true"





