version: "3"

services:

  reverse-proxy:
    image: nginx:1.21.3
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./templates:/etc/nginx/templates
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./www.lzytest.tech_bundle.pem:/etc/nginx/server.pem
      - ./www.lzytest.tech.key:/etc/nginx/server.key
    ports:
      - "80:80"
      - "443:443"
    # environment:
    #   - NGINX_PORT=80

  # origin:
  #   image: python
  #   entrypoint: bash -c "mkdir /app && cd /app && echo 'It works!' > index.html && python -m http.server 80"
  origin:
    image: python:3.6.9-alpine
    volumes:
      - /home/lzy/pcap/nginx:/pcap
      - /home/lzy/logs/nginx:/logs
      - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
      - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
      - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
      # - /home/lzy/my_repo/http2smuggler/echo_server/sleep.py:/sleep.py
    command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"



