version: "3"

services:
  reverse-proxy:
    image: envoyproxy/envoy-alpine:v1.21.6
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - E://tf_practice//WebSecurity//http2test//reverse_pcap//envoy:/pcap
    ports:
      - "80:80"

  # origin:
  #   image: python
  #   entrypoint: bash -c "mkdir /app && cd /app && echo 'Origin works!' > index.html && python -m http.server 80"


  origin:
    image: python:3.6.9-alpine
    volumes:
      - E://tf_practice//WebSecurity//http2test//pcap//envoy:/pcap
      - E://tf_practice//WebSecurity//http2test//logs//envoy:/logs
      - E://tf_practice//WebSecurity//http2test//echo_server//echo_server.py:/echo_server.py
      - E://tf_practice//WebSecurity//http2test//echo_server//requirements.txt:/requirements.txt
      - E://tf_practice//WebSecurity//http2test//echo_server//test_tcpdump.py:/test_tcpdump.py
    command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
