version: "3"

services:

  reverse-proxy:
    image: envoyproxy/envoy:v1.21.6
    volumes:
      # - ./reverse_proxy.yaml:/etc/envoy/envoy.yaml
      - ./envoy.yaml:/etc/envoy/envoy.yaml

    ports:
      # - "80:80"
      - "443:443"

  origin:
    image: python:3.6.9-alpine
    volumes:
      - /home/lzy/pcap/envoy:/pcap
      - /home/lzy/logs/envoy:/logs
      - /home/lzy/my_repo/http2smuggler/echo_server/echo_server.py:/echo_server.py
      - /home/lzy/my_repo/http2smuggler/echo_server/requirements.txt:/requirements.txt
      - /home/lzy/my_repo/http2smuggler/echo_server/test_tcpdump.py:/test_tcpdump.py
      # - /home/lzy/my_repo/http2smuggler/echo_server/sleep.py:/sleep.py
    command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"
