version: "3"

services:

  reverse-proxy:
    image: nginx:1.23-alpine3.17
    volumes:

      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
      - E://tf_practice//WebSecurity//http2test//reverse_pcap//nginx:/pcap

    ports:
      - "80:80"


  # origin:
  #   image: python
  #   entrypoint: bash -c "mkdir /app && cd /app && echo 'Origin works!' > index.html && python -m http.server 80"
  origin:
    image: python:3.6.9-alpine
    volumes:
      - E://tf_practice//WebSecurity//http2test//pcap//nginx:/pcap
      - E://tf_practice//WebSecurity//http2test//logs//nginx:/logs
      - E://tf_practice//WebSecurity//http2test//echo_server//echo_server.py:/echo_server.py
      - E://tf_practice//WebSecurity//http2test//echo_server//requirements.txt:/requirements.txt
      - E://tf_practice//WebSecurity//http2test//echo_server//test_tcpdump.py:/test_tcpdump.py
    command: sh -c "apk update && apk add tcpdump && python3 -m pip install -r requirements.txt && (python3 echo_server.py & python3 test_tcpdump.py)"

 

